/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fd_2022_10_25_piedrapapeltijera;

import java.util.Random;

/**
 *
 * @author aa511
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    
    //Aquí declaramos variables y constantes que podemos usar en todo frame
    int FiguraUsuario, FiguraCompu;
    
    
    public JFramePrincipal() {
        initComponents();

    //Este código se ejecuta antes de que el usuario interactúe
    ocultar();
    }
    
    //Aqui van las funciones
    public void ocultar() //Oculta las etiquetas
    {
        jLabelPiedraU.setVisible(false);
        jLabelPapelU.setVisible(false);
        jLabelTijeraU.setVisible(false);
        
        jLabelPiedraC.setVisible(false);
        jLabelPapelC.setVisible(false);
        jLabelTijeraC.setVisible(false);
        
        jLabelGanaU.setVisible(false);
        jLabelGanaC.setVisible(false);
        jLabelEmpate.setVisible(false);
    }
    
    public void jugar()
    {
        ocultar();
        //Mostrar figura del usuario
        switch(FiguraUsuario)
        {
            case 0: jLabelPiedraU.setVisible(true); break;
            case 1: jLabelPapelU.setVisible(true); break;
            case 2: jLabelTijeraU.setVisible(true); break;
        }
        
        //Seleccionar aleatoriamente la figura de la compu
        Random azar = new Random();
        FiguraCompu = azar.nextInt(3); //Asigna un número entre 0 y 2
        
        //Mostrar figura de la compu
        switch(FiguraCompu)
        {
            case 0: jLabelPiedraC.setVisible(true); break;
            case 1: jLabelPapelC.setVisible(true); break;
            case 2: jLabelTijeraC.setVisible(true); break;
        }
        
        //Jugar
        if(FiguraUsuario == FiguraCompu)
            jLabelEmpate.setVisible(true);
        else
            if(FiguraUsuario == 0 && FiguraCompu == 2 ||
               FiguraUsuario == 1 && FiguraCompu == 0 ||
               FiguraUsuario == 2 && FiguraCompu == 1)
                jLabelGanaU.setVisible(true);
            else
                jLabelGanaC.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPiedra = new javax.swing.JButton();
        jButtonPapel = new javax.swing.JButton();
        jButtonTijera = new javax.swing.JButton();
        jLabelPiedraU = new javax.swing.JLabel();
        jLabelTijeraU = new javax.swing.JLabel();
        jLabelPapelU = new javax.swing.JLabel();
        jLabelPiedraC = new javax.swing.JLabel();
        jLabelTijeraC = new javax.swing.JLabel();
        jLabelPapelC = new javax.swing.JLabel();
        jLabelGanaU = new javax.swing.JLabel();
        jLabelEmpate = new javax.swing.JLabel();
        jLabelGanaC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonPiedra.setBackground(new java.awt.Color(255, 255, 204));
        jButtonPiedra.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonPiedra.setText("Piedra");
        jButtonPiedra.setOpaque(true);
        jButtonPiedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPiedraActionPerformed(evt);
            }
        });

        jButtonPapel.setBackground(new java.awt.Color(255, 255, 204));
        jButtonPapel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonPapel.setText("Papel");
        jButtonPapel.setOpaque(true);
        jButtonPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPapelActionPerformed(evt);
            }
        });

        jButtonTijera.setBackground(new java.awt.Color(255, 255, 204));
        jButtonTijera.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonTijera.setText("Tijera");
        jButtonTijera.setOpaque(true);
        jButtonTijera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTijeraActionPerformed(evt);
            }
        });

        jLabelPiedraU.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPiedraU.setForeground(new java.awt.Color(0, 0, 255));
        jLabelPiedraU.setText("Piedra usuario");

        jLabelTijeraU.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTijeraU.setForeground(new java.awt.Color(0, 0, 255));
        jLabelTijeraU.setText("Tijera usuario");

        jLabelPapelU.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPapelU.setForeground(new java.awt.Color(0, 0, 255));
        jLabelPapelU.setText("Papel usuario");

        jLabelPiedraC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPiedraC.setForeground(new java.awt.Color(255, 0, 0));
        jLabelPiedraC.setText("Piedra Compu");

        jLabelTijeraC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTijeraC.setForeground(new java.awt.Color(255, 0, 0));
        jLabelTijeraC.setText("Tijera compu");

        jLabelPapelC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPapelC.setForeground(new java.awt.Color(255, 0, 0));
        jLabelPapelC.setText("Papel compu");

        jLabelGanaU.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelGanaU.setForeground(new java.awt.Color(0, 0, 255));
        jLabelGanaU.setText("GANA USUARIO");

        jLabelEmpate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelEmpate.setText("EMPATE");

        jLabelGanaC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelGanaC.setForeground(new java.awt.Color(255, 0, 0));
        jLabelGanaC.setText("GANA COMPU");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButtonPiedra)
                        .addGap(122, 122, 122)
                        .addComponent(jButtonPapel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonTijera)
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPiedraU)
                            .addComponent(jLabelPiedraC))
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPapelC)
                            .addComponent(jLabelPapelU))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTijeraU)
                            .addComponent(jLabelTijeraC))))
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelGanaC, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelGanaU)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabelEmpate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPiedra)
                    .addComponent(jButtonPapel)
                    .addComponent(jButtonTijera))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPiedraU)
                    .addComponent(jLabelPapelU)
                    .addComponent(jLabelTijeraU))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPiedraC)
                    .addComponent(jLabelPapelC)
                    .addComponent(jLabelTijeraC))
                .addGap(45, 45, 45)
                .addComponent(jLabelGanaU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelGanaC)
                .addGap(18, 18, 18)
                .addComponent(jLabelEmpate)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPapelActionPerformed
        // TODO add your handling code here:
        FiguraUsuario = 1;
        jLabelPapelU.setVisible(true);
        jugar();
    }//GEN-LAST:event_jButtonPapelActionPerformed

    private void jButtonTijeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTijeraActionPerformed
        // TODO add your handling code here:
        FiguraUsuario = 2;
        jLabelTijeraU.setVisible(true);
        jugar();
    }//GEN-LAST:event_jButtonTijeraActionPerformed

    private void jButtonPiedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPiedraActionPerformed
        // TODO add your handling code here:
        FiguraUsuario = 0;
        jLabelPiedraU.setVisible(true);
        jugar();
    }//GEN-LAST:event_jButtonPiedraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPapel;
    private javax.swing.JButton jButtonPiedra;
    private javax.swing.JButton jButtonTijera;
    private javax.swing.JLabel jLabelEmpate;
    private javax.swing.JLabel jLabelGanaC;
    private javax.swing.JLabel jLabelGanaU;
    private javax.swing.JLabel jLabelPapelC;
    private javax.swing.JLabel jLabelPapelU;
    private javax.swing.JLabel jLabelPiedraC;
    private javax.swing.JLabel jLabelPiedraU;
    private javax.swing.JLabel jLabelTijeraC;
    private javax.swing.JLabel jLabelTijeraU;
    // End of variables declaration//GEN-END:variables
}
