/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fd_22130803_proyecto_02;

import java.util.Random;

/**
 *
 * @author alfre
 */
public class FD_22130803_Frame_02 extends javax.swing.JFrame {

    /**
     * Creates new form FD_22130803_Frame_02
     */
    public FD_22130803_Frame_02() {
        initComponents();
        
        //Ocultamos la etiqueta de incorrectos antes de interactuar con el usuario
        jLabelIncorrectos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextNumDia = new javax.swing.JTextField();
        jTextNumMes = new javax.swing.JTextField();
        jTextNumAnio = new javax.swing.JTextField();
        jTextFormato = new javax.swing.JTextField();
        jButtonVerificar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonAleatorios = new javax.swing.JButton();
        jButtonEjemplo1 = new javax.swing.JButton();
        jButtonEjemplo2 = new javax.swing.JButton();
        jButtonEjemplo3 = new javax.swing.JButton();
        jLabelValidacion = new javax.swing.JLabel();
        jLabelFechaFormato = new javax.swing.JLabel();
        jLabelIncorrectos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("PROYECTO 2 - PUENTES VARGAS ALFREDO - 22130803");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("PROGRAMA QUE VERIFICA SI UNA FECHA ES VÁLIDA PARA POSTERIORMENTE MOSTRARLA EN EL FORMATO SOLICITADO");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fd_22130803_proyecto_02/asignacion.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("H) Diseñar un algoritmo y su correspondiente aplicación");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("visual en Java para verificar si una fecha dada es válida o no,");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("incluyendo para años bisiestos. La fecha se proporciona en");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("tres partes, es decir, día, mes y año. Si la fecha es válida,");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("mostrarla en formato corto o largo a petición del usuario.");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("INGRESE LOS DATOS QUE SE SOLICITAN");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Día en número:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 255));
        jLabel11.setText("Mes en número:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 255));
        jLabel12.setText("Año a cuatro dígitos:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 255));
        jLabel13.setText("Formato de fecha:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 255));
        jLabel14.setText("(Ingrese L para largo y C para corto)");

        jButtonVerificar.setText("VERIFICAR");
        jButtonVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerificarActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("BORRAR");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonAleatorios.setText("ALEATORIOS");
        jButtonAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAleatoriosActionPerformed(evt);
            }
        });

        jButtonEjemplo1.setText("EJEMPLO 1");
        jButtonEjemplo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjemplo1ActionPerformed(evt);
            }
        });

        jButtonEjemplo2.setText("EJEMPLO 2");
        jButtonEjemplo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjemplo2ActionPerformed(evt);
            }
        });

        jButtonEjemplo3.setText("EJEMPLO 3");
        jButtonEjemplo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjemplo3ActionPerformed(evt);
            }
        });

        jLabelValidacion.setBackground(new java.awt.Color(255, 255, 255));
        jLabelValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelValidacion.setOpaque(true);

        jLabelFechaFormato.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFechaFormato.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFechaFormato.setOpaque(true);

        jLabelIncorrectos.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabelIncorrectos.setForeground(new java.awt.Color(255, 51, 51));
        jLabelIncorrectos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIncorrectos.setText("Los datos ingresados son incorrectos o están escritos en un formato erróneo, inténtelo de nuevo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelIncorrectos, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelValidacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(45, 45, 45)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextFormato, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextNumAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextNumMes, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextNumDia, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(82, 82, 82)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jButtonVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonAleatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(40, 40, 40)
                                                    .addComponent(jButtonEjemplo1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jButtonEjemplo2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jButtonEjemplo3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(jLabelFechaFormato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextNumDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVerificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextNumMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextNumAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAleatorios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEjemplo1)
                    .addComponent(jButtonEjemplo2)
                    .addComponent(jButtonEjemplo3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(44, 44, 44)
                .addComponent(jLabelValidacion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFechaFormato, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelIncorrectos)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerificarActionPerformed
        //BOTON VERIFICAR
        
        //Declaración de variables
        int NumDia, NumMes, NumAnio, DiasMes;
        char Formato;
        String MesCorto, MesLargo;
        
        //Entrada de datos
        NumDia = Integer.parseInt(jTextNumDia.getText());
        NumMes = Integer.parseInt(jTextNumMes.getText());
        NumAnio = Integer.parseInt(jTextNumAnio.getText());
        Formato = jTextFormato.getText().charAt(0);
        
        //Comprobamos que los datos sean correctos
        if(NumDia <= 31 && NumDia >= 1 && NumMes <= 12 && NumMes >= 1 && NumAnio <= 9999 && NumAnio >= 0001 && Formato == 'L' || Formato == 'C')
        {
            //Averiguamos cuantos dias tiene el mes ingresado por el usuario
            //Preguntamos si el mes tiene 31 dias
            if(NumMes == 1 || NumMes == 3 || NumMes == 5 || NumMes == 7 || NumMes == 8 || NumMes == 10 || NumMes == 12)
            {
                DiasMes = 31;
            }
            else
            {
                //Preguntamos si el mes es Febrero
                if(NumMes == 2)
                {
                    //Preguntamos si el año es bisiesto
                    if (NumAnio % 4 == 0)
                    {
                        DiasMes = 29;
                    }
                    else
                    {
                        DiasMes = 28;
                    }
                }
                else
                {
                    DiasMes = 30;
                }
            }
            
            //Averiguamos si la fecha es válida
            if(NumDia <= 31 && DiasMes == 31 || NumDia <= 30 && DiasMes == 30 || NumDia <= 29 && DiasMes == 29 || NumDia <= 28 && DiasMes == 28)
            {
                jLabelValidacion.setText("La fecha ingresada es válida");
                //Preguntamos si el formato es largo (L) o corto (C)
                if(Formato == 'C')
                {
                    //Le asignamos el nombre del mes correspondiente
                    switch(NumMes)
                    {
                        case 1: MesCorto = "Ene"; break;
                        case 2: MesCorto = "Feb"; break;
                        case 3: MesCorto = "Mar"; break;
                        case 4: MesCorto = "Abr"; break;
                        case 5: MesCorto = "May"; break;
                        case 6: MesCorto = "Jun"; break;
                        case 7: MesCorto = "Jul"; break;
                        case 8: MesCorto = "Ago"; break;
                        case 9: MesCorto = "Sep"; break;
                        case 10: MesCorto = "Oct"; break;
                        case 11: MesCorto = "Nov"; break;
                        case 12: MesCorto = "Dic"; break;
                        default: MesCorto = "?"; break;
                    }
                    //Salida de datos
                    jLabelFechaFormato.setText("Fecha en formato corto: " + NumDia + "/" + MesCorto + "/" + NumAnio);
                }
                else
                {
                    //Le asignamos el nombre del mes correspondiente
                    switch(NumMes)
                    {
                        case 1: MesLargo = "Enero"; break;
                        case 2: MesLargo = "Febrero"; break;
                        case 3: MesLargo = "Marzo"; break;
                        case 4: MesLargo = "Abril"; break;
                        case 5: MesLargo = "Mayo"; break;
                        case 6: MesLargo = "Junio"; break;
                        case 7: MesLargo = "Julio"; break;
                        case 8: MesLargo = "Agosto"; break;
                        case 9: MesLargo = "Septiembre"; break;
                        case 10: MesLargo = "Octubre"; break;
                        case 11: MesLargo = "Noviembre"; break;
                        case 12: MesLargo = "Diciembre"; break;
                        default: MesLargo = "?"; break;
                    }
                    //Salida de datos
                    jLabelFechaFormato.setText("Fecha en formato largo: " + NumDia + " de " + MesLargo + " de " + NumAnio);
                }
            }
            else
            {
            jLabelValidacion.setText("La fecha ingresada no es válida");
            }
        }
        else
        {
            jLabelIncorrectos.setVisible(true);
        }
    }//GEN-LAST:event_jButtonVerificarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        //BOTON BORRAR
        
        //Borramos los campos de texto
        jTextNumDia.setText("");
        jTextNumMes.setText("");
        jTextNumAnio.setText("");
        jTextFormato.setText("");
        
        //Borramos las etiquetas
        jLabelValidacion.setText("");
        jLabelFechaFormato.setText("");
        
        //Borramos la etiqueta de datos incorrectos
        jLabelIncorrectos.setVisible(false);
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonEjemplo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjemplo1ActionPerformed
         //BOTON EJEMPLO 1
        
        //Asignamos los campos de texto
        jTextNumDia.setText("30");
        jTextNumMes.setText("10");
        jTextNumAnio.setText("2021");
        jTextFormato.setText("C");
        
        //Borramos las etiquetas
        jLabelValidacion.setText("");
        jLabelFechaFormato.setText("");
        
        //Borramos la etiqueta de datos incorrectos
        jLabelIncorrectos.setVisible(false);
    }//GEN-LAST:event_jButtonEjemplo1ActionPerformed

    private void jButtonEjemplo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjemplo2ActionPerformed
        //BOTON EJEMPLO 2
        
        //Asignamos los campos de texto
        jTextNumDia.setText("31");
        jTextNumMes.setText("6");
        jTextNumAnio.setText("1997");
        jTextFormato.setText("L");
        
        //Borramos las etiquetas
        jLabelValidacion.setText("");
        jLabelFechaFormato.setText("");
        
        //Borramos la etiqueta de datos incorrectos
        jLabelIncorrectos.setVisible(false);
    }//GEN-LAST:event_jButtonEjemplo2ActionPerformed

    private void jButtonEjemplo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjemplo3ActionPerformed
        //BOTON EJEMPLO 3
        
        //Asignamos los campos de texto
        jTextNumDia.setText("29");
        jTextNumMes.setText("2");
        jTextNumAnio.setText("2024");
        jTextFormato.setText("L");
        
        //Borramos las etiquetas
        jLabelValidacion.setText("");
        jLabelFechaFormato.setText("");
        
        //Borramos la etiqueta de datos incorrectos
        jLabelIncorrectos.setVisible(false);
    }//GEN-LAST:event_jButtonEjemplo3ActionPerformed

    private void jButtonAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAleatoriosActionPerformed
        //BOTON ALEATORIOS
        
        Random azar = new Random();
        
        //Asignamos los campos de texto
        jTextNumDia.setText(1 + azar.nextInt(32) + "");
        jTextNumMes.setText(1 + azar.nextInt(13) + "");
        jTextNumAnio.setText(1000 + azar.nextInt(10000) + "");
        
        int valor = azar.nextInt(2);
        if(valor == 0)
            jTextFormato.setText("C");
        else
            jTextFormato.setText("L");
        
        //Borramos las etiquetas
        jLabelValidacion.setText("");
        jLabelFechaFormato.setText("");
        
        //Borramos la etiqueta de datos incorrectos
        jLabelIncorrectos.setVisible(false);
    }//GEN-LAST:event_jButtonAleatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FD_22130803_Frame_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FD_22130803_Frame_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FD_22130803_Frame_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FD_22130803_Frame_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FD_22130803_Frame_02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAleatorios;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonEjemplo1;
    private javax.swing.JButton jButtonEjemplo2;
    private javax.swing.JButton jButtonEjemplo3;
    private javax.swing.JButton jButtonVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFechaFormato;
    private javax.swing.JLabel jLabelIncorrectos;
    private javax.swing.JLabel jLabelValidacion;
    private javax.swing.JTextField jTextFormato;
    private javax.swing.JTextField jTextNumAnio;
    private javax.swing.JTextField jTextNumDia;
    private javax.swing.JTextField jTextNumMes;
    // End of variables declaration//GEN-END:variables
}
