/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fd_22130803_proyecto_03;

import javax.swing.JOptionPane;

/**
 *
 * @author alfre
 */
public class FD_22130803_Frame_01 extends javax.swing.JFrame {

    /**
     * Creates new form FD_22130803_Frame_01
     */
    public FD_22130803_Frame_01() {
        initComponents();
    }
    
    //Función que calcula la potencia de cualquier número
    public static double potencia(double base,int exponente)
    {
        //Definición de variables
        double pot;
        int i;
        
        //Asignamos valores de inicio
        pot = 1;
        
        //Ciclo para el procedimiento
        for(i=1; i<=exponente; i++)
            pot = pot * base;
        
        //Regresamos la potencia
        return pot;
    }
    
    //Declaración de variables universales
    int opcion = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonLogaritmoNatural = new javax.swing.JButton();
        jButtonArcoTangente = new javax.swing.JButton();
        jLabelInstruccion = new javax.swing.JLabel();
        jTextNumero = new javax.swing.JTextField();
        jButtonCalcular = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextHistorial = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabelResultado = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fd_22130803_proyecto_03/asignacion.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fd_22130803_proyecto_03/lnx.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fd_22130803_proyecto_03/arcTanx.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("PROYECTO 3 - PUENTES VARGAS ALFREDO - 22130803");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setText("PROGRAMA QUE CALCULA EL LOGARITMO NATURAL (ln) O EL ARCO TANGENTE (ArcTan)  DE UN NÚMERO");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("DISEÑAR UN ALGORITMO Y SU CORRESPONDIENTE APLICACIÓN EN");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("SELECCIONE LA OPERACIÓN QUE DESEA REALIZAR");

        jButtonLogaritmoNatural.setText("Logaritmo Natural (ln)");
        jButtonLogaritmoNatural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogaritmoNaturalActionPerformed(evt);
            }
        });

        jButtonArcoTangente.setText("Arco Tangente (ArcTan)");
        jButtonArcoTangente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArcoTangenteActionPerformed(evt);
            }
        });

        jLabelInstruccion.setBackground(new java.awt.Color(255, 255, 255));
        jLabelInstruccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelInstruccion.setText("(Seleccione una operación para continuar)");

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("HISTORIAL DE OPERACIONES:");

        jTextHistorial.setColumns(20);
        jTextHistorial.setRows(5);
        jScrollPane1.setViewportView(jTextHistorial);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("RESULTADO:");

        jLabelResultado.setBackground(new java.awt.Color(255, 255, 255));
        jLabelResultado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelResultado.setText("(Seleccione una operación e ingrese un número para continuar)");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("JAVA PARA DESARROLLAR UNA \"MINI CALCULADORA\" QUE TENDRÁ 2");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("OPERACIONES DE ENTRE LAS SIGUIENTES:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonLogaritmoNatural, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonArcoTangente, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelInstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextNumero, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonLogaritmoNatural)
                                    .addComponent(jButtonArcoTangente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelInstruccion))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelResultado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCalcular)
                            .addComponent(jButtonBorrar))))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogaritmoNaturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogaritmoNaturalActionPerformed
        //LOGARITMO NATURAL
        
        //Actualizamos la instrucción
        jLabelInstruccion.setText("INGRESE UN NÚMERO ENTRE 2 y 0");
        
        //Borramos campos y etiquetas
        jTextNumero.setText("");
        jLabelResultado.setText("(Seleccione una operación e ingrese un número para continuar)");
        
        //Asignamos la variable opcion
        opcion = 1;
    }//GEN-LAST:event_jButtonLogaritmoNaturalActionPerformed

    private void jButtonArcoTangenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArcoTangenteActionPerformed
        //ARCO TANGENTE
        
        //Actualizamos la instrucción
        jLabelInstruccion.setText("INGRESE UN NÚMERO MENOR QUE 1");
        
        //Borramos campos y etiquetas
        jTextNumero.setText("");
        jLabelResultado.setText("(Seleccione una operación e ingrese un número para continuar)");
        
        //Asignamos la variable opcion
        opcion = 2;
    }//GEN-LAST:event_jButtonArcoTangenteActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        //CALCULAR
        
        //Declaración de variables
        int signo, i, n;
        double x, lnx, arcTanx, suma;
        
        //Realizamos la operación elegida
        switch(opcion)
        {
            case 0://No se seleccionó operación
                //Mostramos mensaje de diálogo
                JOptionPane.showMessageDialog(rootPane, "Seleccione una operación antes de calcular"); break;
            case 1://Logaritmo Natural
                
                //Leemos el dato ingresado
                x = Double.parseDouble(jTextNumero.getText());
        
                //Verificamos si el numero es valido
                if(2 >= x && x > 0 )
                {
                    //Asignamos valores de inicio
                    suma = 0;
                    n = 1;
                    signo = 1;
                    
                    //Ciclo para el procedimiento que se repetirá 25 veces
                    for(i=1; i<=25; i++)
                    {
                        //Realizamos el procedimiento
                        lnx = 1.0/n * potencia((x-1), n) * signo;
                        
                        //Acumulamos la variable suma
                        suma = lnx + suma;
                        
                        //Cambiamos el signo y aumentamos n
                        signo = signo * (-1);
                        n = n + 1;
                    }
                    
                    //Salida de datos
                    jLabelResultado.setText("ln (" + x + ") = " + suma);
                    
                    //Guardamos en el historial
                    jTextHistorial.setText("ln (" + x + ") = " + suma);
                }
                else //El número no es válido
                {
                    //Mostramos mensaje de diálogo
                    JOptionPane.showMessageDialog(rootPane, "El número no es válido, intente de nuevo");
                }       
                break;
            case 2://Arco Tangente
                //Leemos el dato ingresado
                x = Double.parseDouble(jTextNumero.getText());
        
                //Verificamos si el numero es valido
                if(x < 1 && x > -1 )
                {
                    //Asignamos valores de inicio
                    suma = 0;
                    n = 1;
                    signo = 1;
                    
                    //Ciclo para el procedimiento que se repetirá 25 veces
                    for(i=1; i<=25; i++)
                    {
                        //Realizamos el procedimiento
                        arcTanx = (potencia(x,n) / n) * signo;
                        
                        //Acumulamos la variable suma
                        suma = arcTanx + suma;
                        
                        //Cambiamos el signo y aumentamos n
                        signo = signo * (-1);
                        n = n + 2;
                    }
                    //Salida de datos
                    jLabelResultado.setText("arcTan " + x + "° = " + suma);
                    
                    //Guardamos en el historial
                    jTextHistorial.setText("arcTan " + x + "° = " + suma);
                }
                else //El número no es válido
                {
                    //Mostramos mensaje de diálogo
                    JOptionPane.showMessageDialog(rootPane, "El número no es válido, intente de nuevo");
                }
                break;        
        }
        
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        //BORRAR
        
        //Borramos campos y etiquetas
        jLabelInstruccion.setText("(Seleccione una operación para continuar)");
        jTextNumero.setText("");
        jLabelResultado.setText("(Seleccione una operación e ingrese un número para continuar)");
        
        //Devolvemos valor inicial a la variable opcion
        opcion = 0;
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FD_22130803_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FD_22130803_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FD_22130803_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FD_22130803_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FD_22130803_Frame_01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonArcoTangente;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonLogaritmoNatural;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelInstruccion;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextHistorial;
    private javax.swing.JTextField jTextNumero;
    // End of variables declaration//GEN-END:variables
}
