/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fd_22130803_proyecto_01;

import java.util.Random;

/**
 *
 * @author alfre
 */
public class FD_22130803_Frame_01 extends javax.swing.JFrame {

    /**
     * Creates new form FD_22130803_Frame_01
     */
    public FD_22130803_Frame_01() {
        initComponents();
    }
    
    //Función que calcula la Constante Elástica (k)
    public static double ConstanteK(double EM, double m, double v, double h, double x)
    {
        double k, g;
        g = 9.8;
        k = (EM - (m*Math.pow(v,2)/2) - m*g*h) * 2 / Math.pow(x,2);
        return k;
    }
    
    //Función que calcula la Energía Cinética (EC)
    public static double EnergiaC (double m, double v)
    {
        double EC;
        EC = (m*Math.pow(v,2))/2;
        return EC;
    }
    
    //Función que calcula la Energía Potencial Gravitacional (EPG)
    public static double EnergiaPG(double m, double h)
    {
        double EPG, g;
        g = 9.8;
        EPG = (m*g*h);
        return EPG;
    }
    
    //Función que calcula la Energía Potencial Elástica (EPE)
    public static double EnergiaPE( double EM, double EC, double EPG)
    {
        double EPE;
        EPE = (EM - EC - EPG);
        return EPE;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextM1 = new javax.swing.JTextField();
        jTextM2 = new javax.swing.JTextField();
        jTextM3 = new javax.swing.JTextField();
        jTextV1 = new javax.swing.JTextField();
        jTextV2 = new javax.swing.JTextField();
        jTextV3 = new javax.swing.JTextField();
        jTextH1 = new javax.swing.JTextField();
        jTextH2 = new javax.swing.JTextField();
        jTextH3 = new javax.swing.JTextField();
        jTextX1 = new javax.swing.JTextField();
        jTextX2 = new javax.swing.JTextField();
        jTextX3 = new javax.swing.JTextField();
        jTextEM1 = new javax.swing.JTextField();
        jTextEM2 = new javax.swing.JTextField();
        jTextEM3 = new javax.swing.JTextField();
        jButtonEjemplo = new javax.swing.JButton();
        jButtonAleatorio = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonCalcular = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabelK1 = new javax.swing.JLabel();
        jLabelEC1 = new javax.swing.JLabel();
        jLabelEPG1 = new javax.swing.JLabel();
        jLabelEPE1 = new javax.swing.JLabel();
        jLabelPromedio = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabelK2 = new javax.swing.JLabel();
        jLabelEC2 = new javax.swing.JLabel();
        jLabelEPG2 = new javax.swing.JLabel();
        jLabelEPE2 = new javax.swing.JLabel();
        jLabelK3 = new javax.swing.JLabel();
        jLabelEC3 = new javax.swing.JLabel();
        jLabelEPG3 = new javax.swing.JLabel();
        jLabelEPE3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("PROYECTO 1 - PUENTES VARGAS ALFREDO - 22130803");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setText("Programa para calcular un dato a partir de otros 5 datos dados por el usuario");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fd_22130803_proyecto_01/tabla.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fd_22130803_proyecto_01/asignacion.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Ingrese los datos que se solicitan:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Cuerpo");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("1");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("2");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("3");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Masa (m)");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Velocidad (v)");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Altura (h)");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Longitud de estiramiento (x)");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Energía Mecánica (EM)");

        jTextM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextM1ActionPerformed(evt);
            }
        });

        jButtonEjemplo.setText("Ejemplo");
        jButtonEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjemploActionPerformed(evt);
            }
        });

        jButtonAleatorio.setText("Aleatorio");
        jButtonAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAleatorioActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setText("Resultados:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Dato asignado - Constante elástica (k)");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Energía Cinética (EC)");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Energía Potencial Gravitacional (EPG)");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Energía Potencial Elástica (EPE)");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Promedio del dato asignado (k)");

        jLabelK1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelK1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelK1.setOpaque(true);

        jLabelEC1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEC1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelEC1.setOpaque(true);

        jLabelEPG1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEPG1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelEPG1.setOpaque(true);

        jLabelEPE1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEPE1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelEPE1.setOpaque(true);

        jLabelPromedio.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPromedio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelPromedio.setOpaque(true);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel26.setText("Nota:");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel27.setText("Para la realización de los cálculos se tomó en");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel28.setText("cuenta la gravedad (g) con el valor 9.8");

        jLabelK2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelK2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelK2.setOpaque(true);

        jLabelEC2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEC2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelEC2.setOpaque(true);

        jLabelEPG2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEPG2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelEPG2.setOpaque(true);

        jLabelEPE2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEPE2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelEPE2.setOpaque(true);

        jLabelK3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelK3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelK3.setOpaque(true);

        jLabelEC3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEC3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelEC3.setOpaque(true);

        jLabelEPG3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEPG3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelEPG3.setOpaque(true);

        jLabelEPE3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEPE3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelEPE3.setOpaque(true);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Cuerpo 1");

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Cuerpo 2");

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Cuerpo 3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(248, 248, 248))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextM1)
                                        .addComponent(jTextM2)
                                        .addComponent(jTextM3))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextV1)
                                        .addComponent(jTextV2)
                                        .addComponent(jTextV3))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextH1)
                                        .addComponent(jTextH2)
                                        .addComponent(jTextH3)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel20))))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextX1)
                                        .addComponent(jTextX2)
                                        .addComponent(jTextX3)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabelEPE1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelEPG1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelEC1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelK1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabelEPG2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                                .addComponent(jLabelEC2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelK2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelEPE2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextEM1)
                                                .addComponent(jTextEM2)
                                                .addComponent(jTextEM3))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jButtonEjemplo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButtonAleatorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButtonBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButtonCalcular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelK3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelEC3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelEPG3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelEPE3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel27)
                                                .addComponent(jLabel26)
                                                .addComponent(jLabel28)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jButtonCalcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextEM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEjemplo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextEM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAleatorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextH3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextEM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBorrar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel21)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelEC1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabelK2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel16)
                                                        .addComponent(jLabelK1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabelK3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel17)
                                                        .addComponent(jLabelEC2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabelEC3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel18)
                                                .addComponent(jLabelEPG2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabelEPG3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabelEPG1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabelEPE2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelEPE3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelEPE1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabelPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextM1ActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        //Declaración de variables
        double m1, v1, h1, x1, k1, EC1, EPG1, EPE1, EM1,
               m2, v2, h2, x2, k2, EC2, EPG2, EPE2, EM2,
               m3, v3, h3, x3, k3, EC3, EPG3, EPE3, EM3,
               g, Promedio;
        
        //Entrada de datos
        m1 = Double.parseDouble(jTextM1.getText());
        m2 = Double.parseDouble(jTextM2.getText());
        m3 = Double.parseDouble(jTextM3.getText());
        
        v1 = Double.parseDouble(jTextV1.getText());
        v2 = Double.parseDouble(jTextV2.getText());
        v3 = Double.parseDouble(jTextV3.getText());
        
        h1 = Double.parseDouble(jTextH1.getText());
        h2 = Double.parseDouble(jTextH2.getText());
        h3 = Double.parseDouble(jTextH3.getText());
        
        x1 = Double.parseDouble(jTextX1.getText());
        x2 = Double.parseDouble(jTextX2.getText());
        x3 = Double.parseDouble(jTextX3.getText());
        
        EM1 = Double.parseDouble(jTextEM1.getText());
        EM2 = Double.parseDouble(jTextEM2.getText());
        EM3 = Double.parseDouble(jTextEM3.getText());
        
        //Calculamos la constante elástica (k) con la función ConstanteK
        k1 = ConstanteK(EM1, m1, v1, h1, x1);
        k2 = ConstanteK(EM2, m2, v2, h2, x2);
        k3 = ConstanteK(EM3, m3, v3, h3, x3);
        
        //Calculamos la Energía Cinética (EC) con la función EnergiaC
        EC1 = EnergiaC(m1, v1);
        EC2 = EnergiaC(m2, v2);
        EC3 = EnergiaC(m3, v3);
        
        //Calculamos la Energía Potencial Gravitacional (EPG) con la función EnergiaPG
        EPG1 = EnergiaPG(m1, h1);
        EPG2 = EnergiaPG(m2, h2);
        EPG3 = EnergiaPG(m3, h3);
        
        //Calculamos la Energía Potencial Elástica (EPE) con la función EnergiaPE
        EPE1 = EnergiaPE(EM1, EC1, EPG1);
        EPE2 = EnergiaPE(EM2, EC2, EPG2);
        EPE3 = EnergiaPE(EM3, EC3, EPG3);
        
        //Calculamos el promedio de nuestro dato (k)
        Promedio = (k1 + k2 + k3) / 3;
        
        //Salida de datos
        jLabelK1.setText(k1 + "");
        jLabelK2.setText(k2 + "");
        jLabelK3.setText(k3 + "");
        
        jLabelEC1.setText(EC1 + "");
        jLabelEC2.setText(EC2 + "");
        jLabelEC3.setText(EC3 + "");
        
        jLabelEPG1.setText(EPG1 + "");
        jLabelEPG2.setText(EPG2 + "");
        jLabelEPG3.setText(EPG3 + "");
        
        jLabelEPE1.setText(EPE1 + "");
        jLabelEPE2.setText(EPE2 + "");
        jLabelEPE3.setText(EPE3 + "");
        
        jLabelPromedio.setText(Promedio + "");
        
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jButtonEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjemploActionPerformed
        jTextM1.setText(100 + "");
        jTextM2.setText(50 + "");
        jTextM3.setText(70 + "");
        
        jTextV1.setText(1.5 + "");
        jTextV2.setText(3.8 + "");
        jTextV3.setText(2.7 + "");
        
        jTextH1.setText(54 + "");
        jTextH2.setText(12 + "");
        jTextH3.setText(18 + "");
        
        jTextX1.setText(2.8 + "");
        jTextX2.setText(3.9 + "");
        jTextX3.setText(1.6 + "");
        
        jTextEM1.setText(56952.50 + "");
        jTextEM2.setText(17648.50 + "");
        jTextEM3.setText(13627.15 + "");
        
        jLabelK1.setText("");
        jLabelK2.setText("");
        jLabelK3.setText("");
        
        jLabelEC1.setText("");
        jLabelEC2.setText("");
        jLabelEC3.setText("");
        
        jLabelEPG1.setText("");
        jLabelEPG2.setText("");
        jLabelEPG3.setText("");
        
        jLabelEPE1.setText("");
        jLabelEPE2.setText("");
        jLabelEPE3.setText("");
        
        jLabelPromedio.setText("");
    }//GEN-LAST:event_jButtonEjemploActionPerformed

    private void jButtonAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAleatorioActionPerformed
        Random azar = new Random();
        
        jTextM1.setText(azar.nextInt(40, 200) + "")
        jTextM2.setText(azar.nextInt(40, 200) + "");
        jTextM3.setText(azar.nextInt(40, 200) + "");
        
        jTextV1.setText(azar.nextInt(1, 5) + "");
        jTextV2.setText(azar.nextInt(1, 5) + "");
        jTextV3.setText(azar.nextInt(1, 5) + "");
        
        jTextH1.setText(azar.nextInt(20, 100) + "");
        jTextH2.setText(azar.nextInt(20, 100) + "");
        jTextH3.setText(azar.nextInt(20, 100) + "");
        
        jTextX1.setText(azar.nextInt(1, 5) + "");
        jTextX2.setText(azar.nextInt(1, 5) + "");
        jTextX3.setText(azar.nextInt(1, 5) + "");
        
        jTextEM1.setText(azar.nextInt(2000, 100000) + "");
        jTextEM2.setText(azar.nextInt(2000, 100000) + "");
        jTextEM3.setText(azar.nextInt(2000, 100000) + "");
        
        jLabelK1.setText("");
        jLabelK2.setText("");
        jLabelK3.setText("");
        
        jLabelEC1.setText("");
        jLabelEC2.setText("");
        jLabelEC3.setText("");
        
        jLabelEPG1.setText("");
        jLabelEPG2.setText("");
        jLabelEPG3.setText("");
        
        jLabelEPE1.setText("");
        jLabelEPE2.setText("");
        jLabelEPE3.setText("");
        
        jLabelPromedio.setText("");
    }//GEN-LAST:event_jButtonAleatorioActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        jTextM1.setText("");
        jTextM2.setText("");
        jTextM3.setText("");
        
        jTextV1.setText("");
        jTextV2.setText("");
        jTextV3.setText("");
        
        jTextH1.setText("");
        jTextH2.setText("");
        jTextH3.setText("");
        
        jTextX1.setText("");
        jTextX2.setText("");
        jTextX3.setText("");
        
        jTextEM1.setText("");
        jTextEM2.setText("");
        jTextEM3.setText("");
        
        jLabelK1.setText("");
        jLabelK2.setText("");
        jLabelK3.setText("");
        
        jLabelEC1.setText("");
        jLabelEC2.setText("");
        jLabelEC3.setText("");
        
        jLabelEPG1.setText("");
        jLabelEPG2.setText("");
        jLabelEPG3.setText("");
        
        jLabelEPE1.setText("");
        jLabelEPE2.setText("");
        jLabelEPE3.setText("");
        
        jLabelPromedio.setText("");
        
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FD_22130803_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FD_22130803_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FD_22130803_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FD_22130803_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FD_22130803_Frame_01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAleatorio;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonEjemplo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelEC1;
    private javax.swing.JLabel jLabelEC2;
    private javax.swing.JLabel jLabelEC3;
    private javax.swing.JLabel jLabelEPE1;
    private javax.swing.JLabel jLabelEPE2;
    private javax.swing.JLabel jLabelEPE3;
    private javax.swing.JLabel jLabelEPG1;
    private javax.swing.JLabel jLabelEPG2;
    private javax.swing.JLabel jLabelEPG3;
    private javax.swing.JLabel jLabelK1;
    private javax.swing.JLabel jLabelK2;
    private javax.swing.JLabel jLabelK3;
    private javax.swing.JLabel jLabelPromedio;
    private javax.swing.JTextField jTextEM1;
    private javax.swing.JTextField jTextEM2;
    private javax.swing.JTextField jTextEM3;
    private javax.swing.JTextField jTextH1;
    private javax.swing.JTextField jTextH2;
    private javax.swing.JTextField jTextH3;
    private javax.swing.JTextField jTextM1;
    private javax.swing.JTextField jTextM2;
    private javax.swing.JTextField jTextM3;
    private javax.swing.JTextField jTextV1;
    private javax.swing.JTextField jTextV2;
    private javax.swing.JTextField jTextV3;
    private javax.swing.JTextField jTextX1;
    private javax.swing.JTextField jTextX2;
    private javax.swing.JTextField jTextX3;
    // End of variables declaration//GEN-END:variables
}
